# Generated by Django 5.1 on 2024-08-16 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20240816_0402'),
    ]

    operations = [
    ]
