# Generated by Django 5.1 on 2024-08-17 18:34
from django.db import migrations

def populate_role(apps, schema_editor):
    entries = {
        "member": "A member on the site",
        "editor": "Someone who can edit others posts",
        "moderator": "Someone who can edit posts and moderate editors"
    }
    Role = apps.get_model("accounts", "Role")
    for key, value in entries.items():
        Role.objects.get_or_create(name=key, defaults={'description': value})

def populate_team(apps, schema_editor):
    entries = {
        "alpha": "The A team",
        "bravo": "The B team",
        "charlie": "The C team"
    }
    Team = apps.get_model("accounts", "Team")
    for key, value in entries.items():
        Team.objects.get_or_create(name=key, defaults={'description': value})

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_role),
        migrations.RunPython(populate_team),
    ]
